# Generated by Django 4.2.3 on 2023-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="blogs"),
        ),
    ]
